### ISSUE TITLE
Compiling issue 

### ISSUE THREAD

**Issue by ZetOmega** [SpaceCat-Chan/Computercraft-Websocket-Controller#8]
I am no a pro so this might be an easy fix on my side. Basically cmake gives me an error...
I have never compiled c++ before so i'm probably doing something wrong... It looks like pthread.h is missing but neither do I know what it is or where to get it EDIT: I am on windows
[CMakeOutput.log](https://github.com/SpaceCat-Chan/Computercraft-Websocket-Controller/files/6176241/CMakeOutput.log)
[CMakeError.log](https://github.com/SpaceCat-Chan/Computercraft-Websocket-Controller/files/6176242/CMakeError.log)

**Comment by SpaceCat-Chan** [comment]
i am not very familiar with MSVC and visual studio, but it seems like it is trying to find pthread, pthread does not exist on windows

i do not know how to fix this, maybe using a different compiler would work, maybe a different version of CMake

i do know that if you somehow manage to solve this issue, and you are still using MSVC, then you will need to remove line 19 in src/CMakeLists.txt

**Comment by ZetOmega** [comment]
I went through hours of documentation but couldn't find anything. (by removing line 19, I  get these errors:
[CMakeError.log](https://github.com/SpaceCat-Chan/Computercraft-Websocket-Controller/files/6181723/CMakeError.log)
[CMakeOutput.log](https://github.com/SpaceCat-Chan/Computercraft-Websocket-Controller/files/6181724/CMakeOutput.log) ) Did you compile it on Linux?

**Comment by SpaceCat-Chan** [comment]
yes, i haven't tested any of this on windows, but i don't see any reason why it shouldn't work

**Comment by ZetOmega** [comment]
would it be possible for you to upload a compiled version? I spend so much time trying to get it to work, but it just doesn't want to...

**Comment by SpaceCat-Chan** [comment]
i can, but i don't have access to a windows computer right now, are you able to run linux compiled binaries?

i will have access to a windows computer next week

**Comment by ZetOmega** [comment]
I have actually never tried, but i have a spare machine i could install linux on.

**Comment by SpaceCat-Chan** [comment]
you can also try and install WSL and running through that

**Comment by ZetOmega** [comment]
I'll do

**Comment by SpaceCat-Chan** [comment]
you can also try compiling through wsl, all the dependencies are available through ubuntu's apt package manager

**Comment by SpaceCat-Chan** [comment]
i wonder if this issue has been fixed, i'll close it for now.

if there are still problems, please reopen the issue
